### ISSUE TITLE
Model Checkpoints

### ISSUE THREAD

**Issue by simonschoenhofen** [Cuberick-Orion/Bi-Blip4CIR#1]
Hello! 

Your work looks great, I have been working on a blip retrieval and want to now add a composed retrieval aswell. 
I want to ask if you have any timeline on when you release the model checkpoint? 

Sadly I just do not have the gpu capacity to train a model like this. 

Thank you! And thanks for the work!

**Comment by Cuberick-Orion** [comment]
Hi,

The trained checkpoints on both datasets are available in our README [here](https://github.com/Cuberick-Orion/Bi-Blip4CIR#checkpoints).

Best,
David.

**Comment by simonschoenhofen** [comment]
Thanks so much! 
Sorrry, i did not see it, since there is this part in the README :D 

> Code and checkpoints will be released shortly [here](https://github.com/Cuberick-Orion/Candidate-Reranking-CIR).
